FROM  python:3.10.6

ENV PYTHONUNBUFFERED=1

WORKDIR /backend

RUN pip install django django-cors-headers

COPY . . 
# copy from the current directory of the Dockerfile to /api in the image

EXPOSE 8000