# Generated by Django 4.1.7 on 2023-03-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='StopPoint',
        ),
    ]
