# Generated by Django 4.1.7 on 2023-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_rename_stoppoint_busstops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstops',
            name='description',
        ),
        migrations.AddField(
            model_name='busstops',
            name='lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busstops',
            name='long',
            field=models.TextField(blank=True, null=True),
        ),
    ]
