# Generated by Django 4.1.7 on 2023-03-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0004_remove_busstops_description_busstops_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstops',
            name='completed',
        ),
    ]
