# Generated by Django 4.1.7 on 2023-03-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_remove_busstops_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstops',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='busstops',
            old_name='long',
            new_name='longitude',
        ),
    ]
